# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    branches: [ stable ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@stable
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp.seguraaonda.com.br
        ftp-username: seguraaonda.com.br
        ftp-password: ${{ secrets.FTP_PASSWORD }}
